favicon: /img/favicon.png
# Change to your profile picture
avatar: /img/avatar.jpg
# if author sets in hexo_config, this string doesn't work
author: Yiyan Liao
author_bio: Be a rational poet.

since: 2025

# Top Menu 顶部菜单
# #title 为页内跳转，单页模式
# 可以选择外链或其他页面
menu:
  About: /
  Publications: /Publications
  # Github: https://github.com/yiyanliao

# flink picture will load if avator link calls on error
loading_bg:
  flink: /img/profile.png

# Social Links; 社交链接，不需要的链接直接注释掉
# 可以调整显示顺序
# 图标调用 font-awesome 4.7
social:
  enable: true
social_links:
  fab fa-x-twitter: https://x.com/Yiyan_Liao
  # fab fa-facebook-square: /
  fab fa-github: https://github.com/yiyanliao
  # fab fa-stack-overflow: /
  # fab fa-linkedin: /
  # fab fa-weibo: /
  # fab fa-weixin: /
  # fab fa-qq: /
  fas fa-envelope: yiyanliao@stu.pku.edu.cn
  # fas fa-rss: /  #rss

# Additional social_links，额外添加自定义链接，可显示链接名称
# name: url || icon_name
e_social:
  enable: true
e_social_links:
  Google Scholar: https://scholar.google.com/citations?user=9DUJUoQAAAAJ&hl=en || fas fa-graduation-cap
  ORCID: https://orcid.org/my-orcid?orcid=0009-0000-5594-7013 || fab fa-orcid

# CV download link
cv_dl:
  enable: true
  dir: https://raw.githubusercontent.com/yiyanliao/yiyanliao.github.io/main/themes/Academia/source/pdf/CV.pdf
  description: CV as PDF.

# Box-shadow
# display box-shadow on page or not
box_shadow:
  enable: true

# CDN
# 根据需要自行添加js/css
# 自定义css可以直接写在user.styl中
CDN_USE:
  css:
    - /css/index.css
#    - https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
    # - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.min.css # fontawesome 5
    - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6/css/all.min.css
  js:
    - https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js #/js/third-party/jquery.min.js
    - https://cdn.jsdelivr.net/npm/jquery-pjax@latest/jquery.pjax.min.js
    - /js/main.js